stages:
  - build
  - test

run_cypress_tests:
  image: cypress/browsers:node12.14.1-chrome85-ff81
  stage: test
  rules:
    - changes:
      - apps/validation_framework_v2/**/*
  script:
    - cd apps/validation_framework_v2
    # install dependencies
    - npm ci
    # start server and run Cypress tests
    - npm run e2e:ci
  tags:
    - docker-runner

build_apps_staging_image:
  stage: build
  rules:
      - if: '$CI_COMMIT_REF_NAME == "staging"'
        changes:
          - apps/**/*
  script:
    - docker build -f apps/deployment/Dockerfile.staging -t docker-registry.ebrains.eu/model-catalog/model-catalog-v2:staging ./apps
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_SECRET docker-registry.ebrains.eu
    - docker push docker-registry.ebrains.eu/model-catalog/model-catalog-v2:staging
  tags:
    - shell-runner

build_apps_prod_image:
  stage: build
  rules:
      - if: '$CI_COMMIT_REF_NAME == "master"'
        changes:
          - apps/**/*
  script:
    - docker build -f apps/deployment/Dockerfile.prod -t docker-registry.ebrains.eu/model-catalog/model-catalog-v2:prod ./apps
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_SECRET docker-registry.ebrains.eu
    - docker push docker-registry.ebrains.eu/model-catalog/model-catalog-v2:prod
  tags:
    - shell-runner
